# Generated by Django 4.2 on 2023-05-04 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('player_country', models.CharField(max_length=50)),
                ('player_race', models.CharField(choices=[('Terran', 'Terran'), ('Protoss', 'Protoss'), ('Zerg', 'Zerg')], max_length=50)),
                ('rating', models.IntegerField(default=1000)),
                ('rating_v_t', models.IntegerField(default=1000)),
                ('rating_v_z', models.IntegerField(default=1000)),
                ('rating_v_p', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Match_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('player_a_score', models.IntegerField(default=0)),
                ('player_a_rating', models.IntegerField(default=1000)),
                ('player_b_score', models.IntegerField(default=0)),
                ('player_b_rating', models.IntegerField(default=1000)),
                ('player_a_rating_v_t', models.IntegerField(default=1000)),
                ('player_a_rating_v_z', models.IntegerField(default=1000)),
                ('player_a_rating_v_p', models.IntegerField(default=1000)),
                ('player_b_rating_v_t', models.IntegerField(default=1000)),
                ('player_b_rating_v_z', models.IntegerField(default=1000)),
                ('player_b_rating_v_p', models.IntegerField(default=1000)),
                ('best_of', models.IntegerField(default=1)),
                ('player_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_a', to='api.player_stats')),
                ('player_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_b', to='api.player_stats')),
            ],
        ),
    ]
