# Generated by Django 4.2.1 on 2023-05-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_stats',
            name='aligulac_id',
            field=models.IntegerField(default=1),
        ),
    ]
