# Generated by Django 4.2.1 on 2023-06-09 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_player_stats_aligulac_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_stats',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='player_stats',
            name='player_full_name',
            field=models.CharField(default='n/a', max_length=50),
        ),
        migrations.AddField(
            model_name='player_stats',
            name='team',
            field=models.CharField(default='n/a', max_length=20),
        ),
        migrations.AddField(
            model_name='player_stats',
            name='total_earnings',
            field=models.IntegerField(default=0),
        ),
    ]
